"""Notebook generator: produces Databricks-compatible PySpark notebooks."""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from typing import Dict, List, Optional

from flowspark.parser import AlteryxWorkflow, AlteryxTool
from flowspark.mapper import ToolMapper, MappedTool


# ---------------------------------------------------------------------------
# Topology helpers
# ---------------------------------------------------------------------------

def _topological_sort(
    tools: Dict[str, AlteryxTool],
    connections: list,
) -> List[str]:
    """Return tool IDs in topological (execution) order.

    Falls back to insertion order if a cycle is detected.
    """
    from collections import defaultdict, deque

    in_degree: Dict[str, int] = {tid: 0 for tid in tools}
    adj: Dict[str, List[str]] = defaultdict(list)

    for conn in connections:
        src = conn.source_tool_id
        dst = conn.destination_tool_id
        if src in tools and dst in tools:
            adj[src].append(dst)
            in_degree[dst] += 1

    queue: deque = deque(tid for tid, deg in in_degree.items() if deg == 0)
    order: List[str] = []

    while queue:
        tid = queue.popleft()
        order.append(tid)
        for neighbour in adj[tid]:
            in_degree[neighbour] -= 1
            if in_degree[neighbour] == 0:
                queue.append(neighbour)

    # If there are remaining nodes (cycle), append them in stable order
    remaining = [t for t in tools if t not in order]
    order.extend(remaining)
    return order


# ---------------------------------------------------------------------------
# Documentation generator
# ---------------------------------------------------------------------------

def _generate_documentation(
    workflow: AlteryxWorkflow,
    mapped: Dict[str, MappedTool],
) -> str:
    """Return a Markdown string documenting the workflow transformation."""
    lines: List[str] = [
        f"# Workflow: {workflow.name}",
        f"",
        f"> Auto-generated by **FlowSpark** on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total tools | {len(workflow.tools)} |",
        f"| Connections | {len(workflow.connections)} |",
        f"| Macros detected | {len(workflow.macros)} |",
        f"| Unsupported tools | "
        f"{sum(1 for m in mapped.values() if not m.is_supported)} |",
        f"",
        f"## Tool Inventory",
        f"",
        f"| Tool ID | Category | Supported | Notes |",
        f"|---------|----------|-----------|-------|",
    ]

    for tid, mt in mapped.items():
        supported = "✅" if mt.is_supported else "⚠️ Manual"
        lines.append(f"| {tid} | {mt.category} | {supported} | {mt.notes} |")

    if workflow.macros:
        lines += [
            f"",
            f"## Macros Detected",
            f"",
            f"The following tools reference macros and require manual review:",
            f"",
        ]
        for macro_id in workflow.macros:
            tool = workflow.tools.get(macro_id)
            tool_type = tool.tool_type if tool else "unknown"
            lines.append(f"- Tool **{macro_id}** (`{tool_type}`)")

    unsupported = [mt for mt in mapped.values() if not mt.is_supported]
    if unsupported:
        lines += [
            f"",
            f"## Unsupported Components – Manual Review Required",
            f"",
        ]
        for mt in unsupported:
            lines.append(f"- **Tool {mt.tool_id}** ({mt.category}): {mt.notes}")

    lines += [
        f"",
        f"## Connections",
        f"",
        f"| From Tool | Anchor | To Tool | Anchor |",
        f"|-----------|--------|---------|--------|",
    ]
    for conn in workflow.connections:
        lines.append(
            f"| {conn.source_tool_id} | {conn.source_anchor} "
            f"| {conn.destination_tool_id} | {conn.destination_anchor} |"
        )

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Python script generator
# ---------------------------------------------------------------------------

_SCRIPT_HEADER = """\
# Databricks notebook source
# MAGIC %md
# MAGIC # {workflow_name}
# MAGIC
# MAGIC Auto-generated by **FlowSpark** – Alteryx to PySpark Migration Accelerator
# MAGIC Generated: {timestamp}

# COMMAND ----------

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window

spark = SparkSession.builder.getOrCreate()

"""

_UNSUPPORTED_SECTION = """\
# COMMAND ----------
# MAGIC %md
# MAGIC ## ⚠️ Unsupported Tools – Manual Review Required

"""


def _build_python_script(
    workflow: AlteryxWorkflow,
    mapped: Dict[str, MappedTool],
    order: List[str],
) -> str:
    """Render the complete Databricks Python notebook source."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts: List[str] = [
        _SCRIPT_HEADER.format(workflow_name=workflow.name, timestamp=ts)
    ]

    unsupported_ids = [tid for tid in order if not mapped[tid].is_supported]

    if unsupported_ids:
        parts.append(_UNSUPPORTED_SECTION)
        for tid in unsupported_ids:
            parts.append(f"# Tool {tid} ({mapped[tid].category}) – manual migration required\n")
        parts.append("\n")

    parts.append("# COMMAND ----------\n# MAGIC %md\n# MAGIC ## Workflow Steps\n\n")

    for tid in order:
        mt = mapped[tid]
        parts.append(f"# COMMAND ----------\n")
        parts.append(mt.pyspark_snippet)
        parts.append("\n\n")

    return "".join(parts)


# ---------------------------------------------------------------------------
# Jupyter / ipynb generator
# ---------------------------------------------------------------------------

def _make_cell(source: str, cell_type: str = "code") -> dict:
    lines = [line + "\n" for line in source.splitlines()]
    if lines:
        lines[-1] = lines[-1].rstrip("\n")
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": lines,
        **({"outputs": [], "execution_count": None} if cell_type == "code" else {}),
    }


def _build_ipynb(
    workflow: AlteryxWorkflow,
    mapped: Dict[str, MappedTool],
    order: List[str],
) -> str:
    """Render a Jupyter notebook (.ipynb) JSON string."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    cells = [
        _make_cell(
            f"# {workflow.name}\n\nAuto-generated by **FlowSpark**  \nGenerated: {ts}",
            "markdown",
        ),
        _make_cell(
            "from pyspark.sql import SparkSession\n"
            "from pyspark.sql import functions as F\n"
            "from pyspark.sql.window import Window\n\n"
            "spark = SparkSession.builder.getOrCreate()"
        ),
    ]

    unsupported_ids = [tid for tid in order if not mapped[tid].is_supported]
    if unsupported_ids:
        cells.append(
            _make_cell(
                "## ⚠️ Unsupported Tools – Manual Review Required\n\n"
                + "\n".join(
                    f"- Tool **{tid}** ({mapped[tid].category})" for tid in unsupported_ids
                ),
                "markdown",
            )
        )

    for tid in order:
        mt = mapped[tid]
        cells.append(_make_cell(f"### Tool {tid}: {mt.category}", "markdown"))
        cells.append(_make_cell(mt.pyspark_snippet))

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"},
        },
        "cells": cells,
    }
    return json.dumps(notebook, indent=2)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class NotebookGenerator:
    """Generate Databricks-compatible PySpark notebooks from a workflow.

    Usage::

        parser = AlteryxParser()
        workflow = parser.parse_file("workflow.yxmd")

        mapper = ToolMapper()
        mapped = mapper.map_workflow(workflow)

        gen = NotebookGenerator()
        gen.generate(workflow, mapped, output_dir="output/")
    """

    def generate(
        self,
        workflow: AlteryxWorkflow,
        mapped: Optional[Dict[str, MappedTool]] = None,
        output_dir: str = ".",
        formats: Optional[List[str]] = None,
    ) -> Dict[str, str]:
        """Generate all output artefacts for *workflow*.

        Parameters
        ----------
        workflow:
            Parsed Alteryx workflow.
        mapped:
            Pre-computed tool mapping.  If *None* a :class:`ToolMapper` is
            instantiated automatically.
        output_dir:
            Directory where artefact files are written.
        formats:
            List of formats to produce.  Supported values:
            ``"py"`` (Databricks notebook), ``"ipynb"`` (Jupyter notebook),
            ``"md"`` (Markdown documentation).  Defaults to all three.

        Returns
        -------
        dict
            ``{format: file_path}`` for every artefact written.
        """
        if mapped is None:
            mapped = ToolMapper().map_workflow(workflow)

        if formats is None:
            formats = ["py", "ipynb", "md"]

        os.makedirs(output_dir, exist_ok=True)
        order = _topological_sort(workflow.tools, workflow.connections)

        # Ensure every tool_id in order exists in mapped (safety guard)
        order = [tid for tid in order if tid in mapped]

        written: Dict[str, str] = {}

        if "py" in formats:
            content = _build_python_script(workflow, mapped, order)
            path = os.path.join(output_dir, f"{workflow.name}.py")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            written["py"] = path

        if "ipynb" in formats:
            content = _build_ipynb(workflow, mapped, order)
            path = os.path.join(output_dir, f"{workflow.name}.ipynb")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            written["ipynb"] = path

        if "md" in formats:
            content = _generate_documentation(workflow, mapped)
            path = os.path.join(output_dir, f"{workflow.name}.md")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            written["md"] = path

        return written

    def generate_documentation(
        self,
        workflow: AlteryxWorkflow,
        mapped: Optional[Dict[str, MappedTool]] = None,
    ) -> str:
        """Return a Markdown documentation string for the workflow."""
        if mapped is None:
            mapped = ToolMapper().map_workflow(workflow)
        return _generate_documentation(workflow, mapped)
